services:
    sithous.antispam:
        class:     Sithous\AntiSpamBundle\Service\AntiSpamService
        arguments: [ '@doctrine.orm.entity_manager', '@security.token_storage', '%sithous_anti_spam%' ]